## Numpy
- 파이썬에서 수학적 계산 또는 행렬 또는 차원을 다룰 때 자주 사용되는 라이브러리 입니다.

### Numpy - 기초

In [ ]:
# install
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# import
import numpy as np

In [ ]:
array1 = np.array([1,2,3]) # 1차원 배열 - 하나의 컬럼 데이터
array2 = np.array([[1,2,3], [1,2,3]]) # 2차원 배열 - 행과 열이 포함된 데이터

array1
array2

array1.shape
array2.shape # (2,3) => 2행 3열

array1.ndim
array2.ndim

2

In [ ]:
array3 = np.array(
    [ [ ["A", "B", "C"] ] ]
)

print(array3.ndim) # 차원
print(array3.shape) # 차원의 요소 개수 (행, 열)
print(array3.dtype) # 타입 -> 공통적인 데이터 타입

3
(1, 1, 3)
<U1


### ndarray 데이터 타입

In [ ]:
list2 = [1 , 2 , 'c']

arr2 = np.array(list2)
print(arr2.dtype)

list3 = [1.0, 2.0, 3]
arr3 = np.array(list3)
print(arr3.dtype)

<U21
float64


In [ ]:
array4 = np.array(["1","2","3","4","5"])
array4.dtype # 문자열 데이터

array4 = array4.astype(np.int64) # astype
array4.dtype # 정수형 데이터로 변경

dtype('int64')

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') # np.float64

array_float.dtype

array_int1 = array_float.astype('int64')
array_int1.dtype

array_float1 = np.array([1.0, 2.0, 3.1])

array_int2 = array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1 2 3] int64


- Boolean Indexing

In [ ]:
arr = np.arange(10)

# print(arr)
# print(arr.dtype) # 숫자형 데이터 타입
# print(arr.shape) # (10) 10행인 1차원 배열

arr[0:5]

print(arr > 6)
print(arr[arr > 6])

[False False False False False False False  True  True  True]
[7 8 9]


### 인덱싱, 슬라이싱

In [ ]:
arr = np.arange(1,10)
arr

arr[0]
arr[0:5]
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### sort()
- 정렬을 위해 사용하는 함수

In [ ]:
arr = np.array([10, 30, 2, 9, 6])

arr_sorted = np.sort(arr)

print(arr_sorted)
print(arr.sort())

arr_sorted_desc = np.sort(arr)[::-1] # 내림차순 [::-1]
print(arr_sorted_desc)

[ 2  6  9 10 30]
None
[30 10  9  6  2]


In [ ]:
arr = np.array(["Korea", "Singapole", "China", "Japan"])

arr_sorted = np.sort(arr)

print(arr_sorted)

#  유니코드 코드 포인트 값인데 맨 앞글자만 비교.

['China' 'Japan' 'Korea' 'Singapole']


### 행렬의 연산

### Numpy Quiz

- Q1.1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.
- Q2.1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.
- Q3.1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.
- Q4.1차원 배열에서 중복되는 값을 제거하는 코드를 작성하세요.

arr1 = np.arange(10)

In [ ]:
# Q1.1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.



3.0

In [ ]:
# Q2.1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.
# - boolean indexing


array([6, 9, 7, 8])

In [ ]:
# Q3. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.



(array([1, 2, 6, 7]),)


In [ ]:
# Q4. 1차원 배열에서 중복되는 값을 제거하는 코드를 작성하세요.
arr1 = np.array([1,1,1,2,3,3,4,4,4,5])



[1 2 3 4 5]
